name: Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Docker Hub credentials
        run: |
          echo $DOCKER_USERNAME
          echo $DOCKER_PASSWORD
          echo $DOCKER_USERNAME > ~/.docker/config.json
          echo $DOCKER_PASSWORD >> ~/.docker/config.json

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/renegadestation:latest
