name: Build and Push Docker Image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        run: |
          export DOCKER_CONFIG=~/.docker/config.json
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PAT }}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: DockerFileFolder/
          push: true
          tags: renegadestation/renegadestation:latest
