name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: login to docker hub
        id: docker-hub
        env:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}
        run: |
          echo $password | docker login -u $username --password-stdin
      - name: build the docker image
        id: build-docker-image
        run: |
          ls -la 
          docker build . -f Dockerfile -t renegadestation/renegadestation:latest
      - name: push the docker image
        id: push-docker-image
        run: docker push renegadestation/renegadestation:latest
